// 通知系
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

// 非同期取得
export const GET_PRACTICE_REQUEST = 'GET_PRACTICE_REQUEST';
export const GET_PRACTICE_SUCCESS = 'GET_PRACTICE_SUCCESS';
export const GET_PRACTICE_FAILURE = 'GET_PRACTICE_FAILURE';